[book]
authors = ["Abrar Habib", "Shehab Mohsen"]
language = "en"
multilingual = false
src = "src"
title = "Cool Corridors Documentation"
description = "Documentation for using the Cool Corridors API"